services:
  postgres:
    image: 'postgres:16.0-alpine'
    container_name: learning-kotlin-postgresql-db
    environment:
      - POSTGRES_DB=sports_db
      - POSTGRES_USER=sports_db_admin
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_PORT=5431
    ports:
      - '5431:5432'
